[package]
name = "vegafusion-rt-datafusion"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vegafusion-core = {path = "../vegafusion-core", features=["datafusion"]}

regex = "^1.5.4"
lazy_static = "^1.4.0"
serde = {version="1.0.126", features=["derive"]}
serde_json = "1.0.68"
chrono = "0.4.19"
datafusion = { version = "6.0.0" }
prost = "0.8.0"
prost-types = "0.8.0"
num-traits = "0.2.14"
itertools = "0.10.1"
tokio = { version = "1.10.1", features = ["macros", "rt-multi-thread"] }
float-cmp = "0.9.0"
lru = "0.7.0"
futures = "0.3.17"
async-trait = "0.1.51"
async-recursion = "0.3.2"
reqwest = {version="0.11.4", default_features=false, features=["rustls-tls"]}
async-lock = "2.4.0"
tempfile = "3.2.0"
futures-util = "0.3.17"
bytes = "1.1.0"

[dev-dependencies]
reqwest = {version="0.11.4", default_features=false, features=["blocking", "rustls-tls"]}
futures = "0.3.17"
futures-util = "0.3.17"
rstest = "0.11.0"
test-case = "1.2.1"
base64 = "0.13.0"
dssim = "3.1.0"
rgb = "0.8.27"
lodepng = "3.4.6"

