[workspace]

members = [
    "vegafusion-core",
    "vegafusion-rt-datafusion",
    "vegafusion-python",
    "vegafusion-wasm",
]

[profile.release]
## Tell `rustc` to use highest performance optimization and perform Link Time Optimization
opt-level = 3
#lto = true
