[workspace]
resolver = "2"
members = [
    "vegafusion-common",
    "vegafusion-core",
    "vegafusion-runtime",
    "vegafusion-dataframe",
    "vegafusion-datafusion-udfs",
    "vegafusion-sql",
    "vegafusion-python-embed",
    "vegafusion-wasm",
    "vegafusion-server",
    "vegafusion-jni",
]

[workspace.dependencies]
arrow = { version = "50.0.0", default_features = false }
sqlparser = { version = "0.41.0" }
chrono = { version = "0.4.31", default_features = false }
reqwest = { version = "0.11.22", default-features = false }
tokio = { version = "1.36.0" }
pyo3 = { version = "0.20.0" }
pythonize = { version = "0.20.0" }
prost = { version = "0.12.1" }
prost-types = { version = "0.12.1" }
object_store = { version= "0.9.0" }

[workspace.dependencies.datafusion]
version = "36.0.0"

[workspace.dependencies.datafusion-common]
version = "36.0.0"

[workspace.dependencies.datafusion-expr]
version = "36.0.0"

[workspace.dependencies.datafusion-proto]
version = "36.0.0"

[workspace.dependencies.datafusion-physical-expr]
version = "36.0.0"

[workspace.dependencies.datafusion-optimizer]
version = "36.0.0"

[workspace.dependencies.datafusion-functions]
version = "36.0.0"

[profile.release]
## Tell `rustc` to use highest performance optimization and perform Link Time Optimization
opt-level = 3
# lto = true
