[workspace]
resolver = "2"
members = [
    "vegafusion-common",
    "vegafusion-core",
    "vegafusion-runtime",
    "vegafusion-dataframe",
    "vegafusion-datafusion-udfs",
    "vegafusion-sql",
    "vegafusion-python-embed",
    "vegafusion-wasm",
    "vegafusion-server",
    "vegafusion-jni",
]

[workspace.dependencies]
arrow = { version = "49.0.0", default_features = false }
sqlparser = { version = "0.39.0" }
chrono = { version = "0.4.31", default_features = false }
reqwest = { version = "0.11.22", default-features = false }
tokio = { version = "1.32.0" }
pyo3 = { version = "0.20.0" }
pythonize = { version = "0.20.0" }
prost = { version = "0.12.1" }
prost-types = { version = "0.12.1" }
object_store = { version= "0.8.0" }

datafusion = { version = "34.0.0" }
datafusion-common = { version = "34.0.0", default_features = false}
datafusion-expr = { version = "34.0.0" }
datafusion-proto = { version = "34.0.0" }
datafusion-physical-expr = { version = "34.0.0" }
datafusion-optimizer = { version = "34.0.0" }

[profile.release]
## Tell `rustc` to use highest performance optimization and perform Link Time Optimization
opt-level = 3
# lto = true
