[workspace]
resolver = "2"
members = [
    "vegafusion-common",
    "vegafusion-core",
    "vegafusion-runtime",
    "vegafusion-dataframe",
    "vegafusion-datafusion-udfs",
    "vegafusion-sql",
    "vegafusion-python-embed",
    "vegafusion-wasm",
    "vegafusion-server",
    "vegafusion-jni",
]

[workspace.dependencies]
arrow = { version = "46.0.0", default_features = false }
sqlparser = { version = "0.37.0" }
chrono = { version = "0.4.31", default_features = false }
reqwest = { version = "=0.11.13", default-features = false }
tokio = { version = "1.32.0" }
pyo3 = { version = "0.19" }

# # Once datafusion 32.0.0 is released
#datafusion = { version = "32.0.0" }
#datafusion-common = { version = "32.0.0", default_features = false}
#datafusion-expr = { version = "32.0.0" }
#datafusion-proto = { version = "32.0.0" }
#datafusion-physical-expr = { version = "32.0.0" }
#datafusion-optimizer = { version = "32.0.0" }

# # Git dependencies for development
datafusion = { git = "https://github.com/apache/arrow-datafusion.git", rev = "d19e9d684bbe1fd820674d48a96795bfbea9db7d" }
datafusion-common = { git = "https://github.com/apache/arrow-datafusion.git", rev = "d19e9d684bbe1fd820674d48a96795bfbea9db7d", default_features = false}
datafusion-expr = { git = "https://github.com/apache/arrow-datafusion.git", rev = "d19e9d684bbe1fd820674d48a96795bfbea9db7d"  }
datafusion-proto = { git = "https://github.com/apache/arrow-datafusion.git", rev = "d19e9d684bbe1fd820674d48a96795bfbea9db7d"  }
datafusion-physical-expr = { git = "https://github.com/apache/arrow-datafusion.git", rev = "d19e9d684bbe1fd820674d48a96795bfbea9db7d"  }
datafusion-optimizer = { git = "https://github.com/apache/arrow-datafusion.git", rev = "d19e9d684bbe1fd820674d48a96795bfbea9db7d"  }

[profile.release]
## Tell `rustc` to use highest performance optimization and perform Link Time Optimization
opt-level = 3
# lto = true
