[workspace]

members = [
    "vegafusion-common",
    "vegafusion-core",
    "vegafusion-runtime",
    "vegafusion-dataframe",
    "vegafusion-datafusion-udfs",
    "vegafusion-sql",
    "vegafusion-python-embed",
    "vegafusion-wasm",
    "vegafusion-server",
    "vegafusion-jni",
]

[profile.release]
## Tell `rustc` to use highest performance optimization and perform Link Time Optimization
opt-level = 3
# lto = true
