[workspace]

members = [
    "vegafusion-core",
    "vegafusion-rt-datafusion",
    "vegafusion-python-embed",
    "vegafusion-wasm",
    "vegafusion-server",
]

[profile.release]
## Tell `rustc` to use highest performance optimization and perform Link Time Optimization
opt-level = 3
# lto = true

[patch.crates-io]

# Arrow 28.0 with backports
arrow = { git = "https://github.com/jonmmease/arrow-rs.git", rev = "b7a162a8818aa6ded704edec5d7423ee4645e9e2"}
arrow-cast = { git = "https://github.com/jonmmease/arrow-rs.git", rev = "b7a162a8818aa6ded704edec5d7423ee4645e9e2"}
arrow-ipc = { git = "https://github.com/jonmmease/arrow-rs.git", rev = "b7a162a8818aa6ded704edec5d7423ee4645e9e2"}
arrow-data = { git = "https://github.com/jonmmease/arrow-rs.git", rev = "b7a162a8818aa6ded704edec5d7423ee4645e9e2"}
arrow-buffer = { git = "https://github.com/jonmmease/arrow-rs.git", rev = "b7a162a8818aa6ded704edec5d7423ee4645e9e2"}
arrow-schema = { git = "https://github.com/jonmmease/arrow-rs.git", rev = "b7a162a8818aa6ded704edec5d7423ee4645e9e2"}
arrow-array = { git = "https://github.com/jonmmease/arrow-rs.git", rev = "b7a162a8818aa6ded704edec5d7423ee4645e9e2"}
arrow-select = { git = "https://github.com/jonmmease/arrow-rs.git", rev = "b7a162a8818aa6ded704edec5d7423ee4645e9e2"}

# DataFusion 15.0 with backports
datafusion = { git = "https://github.com/jonmmease/arrow-datafusion.git", rev = "36c386188e5affd2360bf05767563f64fb6311fb"}
datafusion-common = { git = "https://github.com/jonmmease/arrow-datafusion.git", rev = "36c386188e5affd2360bf05767563f64fb6311fb"}
datafusion-expr = { git = "https://github.com/jonmmease/arrow-datafusion.git", rev = "36c386188e5affd2360bf05767563f64fb6311fb"}
