[project]
name = "vegafusion"
version = "0.1.0"
description = "Add a short description here"
authors = ["Jon Mease <jonmmease@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "win-64"]

[tasks]
check-rs-fmt = "cargo fmt --all -- --check"
check-rs-warnings = "export RUSTFLAGS=\"-D warnings\" && cargo check --tests"
check-rs-clippy = "cargo clippy -- -A clippy::borrow_deref_ref"

# setup python dev packages
dev-py-embed = { cmd = ["maturin", "develop", "-m", "vegafusion-python-embed/Cargo.toml", "--release"]}
dev-py-vegafusion = { cmd = "cd python/vegafusion && pip install -e . --no-deps", depends_on = ["dev-py-embed"] }
dev-py-jupyter = { cmd = "cd python/vegafusion-jupyter && npm install && npm run build:dev", depends_on = ["dev-py-vegafusion", "dev-py-embed", "build-js-embed"] }

# Build Python packages
build-py-embed = {cmd = "maturin build -m vegafusion-python-embed/Cargo.toml --release --strip $0"}
build-py-vegafusion = {cmd = "cd python/vegafusion && python setup.py sdist bdist_wheel $0"}
build-py-jupyter = {cmd = "cd python/vegafusion-jupyter && python setup.py sdist bdist_wheel $0", depends_on = ["build-js-embed"]}

# test python
test-py-vegafusion = { cmd = "cd python/vegafusion && pytest $0", depends_on = ["dev-py-vegafusion"]}
install-chromedriver-auto = "pip install -U chromedriver-binary-auto"
test-py-jupyter = { cmd = "cd python/vegafusion-jupyter && pytest $0", depends_on = ["dev-py-jupyter", "install-chromedriver-auto"]}
test-py-jupyter-headless = { cmd = "export VEGAFUSION_TEST_HEADLESS=1 && cd python/vegafusion-jupyter && pytest $0", depends_on = ["dev-py-jupyter", "install-chromedriver-auto"]}

# Test rust
build-vegajs-runtime = { cmd = "cd vegafusion-runtime/tests/util/vegajs_runtime && npm install" }
test-rs-core = "cargo test -p vegafusion-core $0"
test-rs-runtime = { cmd="cargo test -p vegafusion-runtime $0",  depends_on = ["build-vegajs-runtime"] }
test-rs-server = "cargo test -p vegafusion-server $0"

# Build Wasm
install-wasm-toolchain = "python automation/download_rust_target.py wasm32-unknown-unknown"
install-wasm-pack = "export CARGO_HOME=$PIXI_PACKAGE_ROOT/.pixi/env && cargo install wasm-pack"
build-wasm = { cmd = "cd vegafusion-wasm && wasm-pack build --release && cp package.json pkg/", depends_on = ["install-wasm-toolchain", "install-wasm-pack"] }

# Install Javascript
build-js-embed = { cmd = "cd javascript/vegafusion-embed && npm install && npm run build", depends_on = ["build-wasm"] }

# VegaFusion Server
build-rs-vegafusion-server = { cmd = "cargo build -p vegafusion-server --release"}

# Java
build-jni = "cargo build -p vegafusion-jni --release $0"
build-jar = "export VEGAFUSION_JNI_LIBRARIES=$1 && cd java && ./gradlew jar"
build-jar-win = "export VEGAFUSION_JNI_LIBRARIES=$1 && cd java && ./gradlew.bat jar"

[tasks.test-java]
cmd = """
export VEGAFUSION_JNI_LIBRARY=$(python automation/find_file.py $PIXI_PACKAGE_ROOT/target/release/ \"libvegafusion_jni\\.(so|dylib)$\") &&
cd java &&
./gradlew test $0
"""
depends_on = ["build-jni"]

[tasks.test-java-win]
cmd = """
export VEGAFUSION_JNI_LIBRARY=$PIXI_PACKAGE_ROOT/target/release/vegafusion_jni.dll &&
cd java &&
./gradlew.bat test $0
"""
depends_on = ["build-jni"]

# Build dependencies are those required to build and test all packages
[build-dependencies]
python = "3.10.*"
nodejs = "20.5.1.*"
maturin = "1.2.3.*"
yarn = "3.6.1.*"
jupyterlab = "4.0.5.*"
nbval = "0.9.6.*"
selenium = "4.11.2.*"
scikit-image = "0.21.0.*"
toml = "0.10.2.*"
pytest = ">=4.6"
click = "8.1.6.*"
python-duckdb = "0.8.1.*"
jupyter-packaging = "0.12.3.*"
pip = "23.2.1.*"
voila = "0.5.0.*"
polars = "0.18.15.*"
tenacity = "8.2.3.*"
pytest-cov = "4.1.0.*"
flaky = "3.7.0.*"
vega_datasets = "0.9.0.*"
rust = "1.71.1.*"
jupytext = "1.15.0.*"
openjdk = "20.0.0.*"


# Dependencies are those required at runtime by the Python packages
[dependencies]
psutil = "5.9.5.*"
pyarrow = "12.0.1.*"
pandas = "2.0.3.*"
altair = "5.0.1.*"
protobuf = "4.23.3.*"
ipywidgets = "8.1.0.*"
vl-convert-python = "0.12.0.*"
