[package]
name = "vegafusion-dataframe"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"

[dependencies.vegafusion-common]
path = "../vegafusion-common"
version = "1.0.3"

[dependencies.datafusion-common]
version = "~17.0.0"

[dependencies.datafusion-expr]
version = "~17.0.0"

[dependencies.arrow]
version = "31.0.0"
default_features = false
