[package]
name = "vegafusion-dataframe"
license = "BSD-3-Clause"
version = "1.5.1"
edition = "2021"
description = "VegaFusion's DataFrame and Connection traits"

[dependencies]
async-trait = "0.1.73"

[dependencies.vegafusion-common]
path = "../vegafusion-common"
version = "1.5.1"

[dependencies.datafusion-common]
workspace = true

[dependencies.datafusion-expr]
workspace = true

[dependencies.arrow]
workspace = true
default_features = false
