[package]
name = "vegafusion-dataframe"
version = "1.0.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.53"

[dependencies.vegafusion-common]
path = "../vegafusion-common"
version = "1.0.3"

[dependencies.datafusion-common]
version = "~16.1.0"
git = "https://github.com/jonmmease/arrow-datafusion.git"
rev = "1e6438de31219b284df9b83f25ca36ddb1184f22"

[dependencies.datafusion-expr]
version = "~16.1.0"
git = "https://github.com/jonmmease/arrow-datafusion.git"
rev = "1e6438de31219b284df9b83f25ca36ddb1184f22"

[dependencies.arrow]
version = "29.0.0"
default_features = false
