[[bin]]
name = "vegafusion-server"
path = "src/main.rs"

[package]
name = "vegafusion-server"
license = "BSD-3-Clause"
version = "1.4.0"
edition = "2021"
description = "VegaFusion Server"

[features]
protobuf-src = [ "vegafusion-core/protobuf-src",]

[dependencies]
prost = "0.12.0"
futures-util = "0.3.21"
regex = "^1.5.5"
hyper = "0.14.27"

[dev-dependencies]
serde_json = "1.0.91"
assert_cmd = "2.0"
predicates = "3.0.2"

[build-dependencies]
tonic-build = "0.10.0"
prost-build = "0.12.0"

[dependencies.vegafusion-common]
path = "../vegafusion-common"
version = "1.4.0"

[dependencies.vegafusion-core]
path = "../vegafusion-core"
features = [ "tonic_support",]
version = "1.4.0"

[dependencies.vegafusion-runtime]
path = "../vegafusion-runtime"
version = "1.4.0"

[dependencies.vegafusion-sql]
path = "../vegafusion-sql"
version = "1.4.0"
features = [ "datafusion-conn",]

[dependencies.tokio]
version = "1.32.0"
features = [ "rt-multi-thread", "macros",]

[dependencies.tonic-web]
version = "0.10.0"

[dependencies.tonic]
version = "0.10.0"
features = [ "tls",]

[dependencies.clap]
version = "4.2.1"
features = [ "derive",]

[target."cfg(target_family = \"unix\")".build-dependencies]
protobuf-src = "1.1.0"
