[[bin]]
name = "vegafusion-server"
path = "src/main.rs"

[package]
name = "vegafusion-server"
license = "BSD-3-Clause"
version = "1.1.3"
edition = "2021"
description = "VegaFusion Server"

[features]
protobuf-src = [ "vegafusion-core/protobuf-src",]

[dependencies]
prost = "0.11.3"
futures-util = "0.3.21"
regex = "^1.5.5"
h2 = "0.3.16"

[dev-dependencies]
serde_json = "1.0.91"
assert_cmd = "2.0"
predicates = "3.0.2"

[build-dependencies]
tonic-build = "0.9.1"
prost-build = "0.11.4"

[dependencies.vegafusion-common]
path = "../vegafusion-common"
version = "1.1.3"

[dependencies.vegafusion-core]
path = "../vegafusion-core"
features = [ "tonic_support",]
version = "1.1.3"

[dependencies.vegafusion-runtime]
path = "../vegafusion-runtime"
version = "1.1.3"

[dependencies.vegafusion-sql]
path = "../vegafusion-sql"
version = "1.1.3"
features = [ "datafusion-conn",]

[dependencies.tokio]
version = "1.27.0"
features = [ "rt-multi-thread", "macros",]

[dependencies.tonic-web]
version = "0.5.0"
git = "https://github.com/hyperium/tonic.git"
rev = "b3358dc6acf11ec800571735de1e1f1e449ec96a"

[dependencies.tonic]
version = "0.8.3"
features = [ "tls",]
git = "https://github.com/hyperium/tonic.git"
rev = "b3358dc6acf11ec800571735de1e1f1e449ec96a"

[dependencies.clap]
version = "3.2.22"
features = [ "derive",]

[target."cfg(target_family = \"unix\")".build-dependencies]
protobuf-src = "1.1.0"
