[package]
name = "vegafusion-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]] # Bin to run the VegaFusion Runtime as gRPC service
name = "vegafusion-server"
path = "src/vegafusion-server.rs"

[dependencies]
vegafusion-core = {path = "../vegafusion-core", features=["datafusion", "tonic_support"]}
vegafusion-rt-datafusion = {path = "../vegafusion-rt-datafusion"}
prost = "0.9.0"
tokio = {version = "1.17.0", features=["rt-multi-thread", "macros"]}
tonic = {version="0.6.2", features=["tls"]}
futures-util="0.3.21"
clap = {version="3.1.0", features=["derive"]}
regex = "1.5.4"
tonic-web = "0.2.0"

[dev-dependencies]
serde_json = "1.0.68"

[build-dependencies]
tonic-build = "0.6"