[[bin]]
name = "vegafusion-server"
path = "src/main.rs"

[package]
name = "vegafusion-server"
version = "1.0.0-rc2"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
prost = "0.11.3"
futures-util = "0.3.21"
regex = "^1.5.5"
tonic-web = "0.5.0"

[dev-dependencies]
serde_json = "1.0.81"
assert_cmd = "2.0"
predicates = "2.1"

[build-dependencies]
tonic-build = "0.8.4"
prost-build = "0.11.4"

[dependencies.vegafusion-core]
path = "../vegafusion-core"
features = [ "tonic_support",]
version = "1.0.0-rc2"

[dependencies.vegafusion-rt-datafusion]
path = "../vegafusion-rt-datafusion"
version = "1.0.0-rc2"

[dependencies.tokio]
version = "1.18.1"
features = [ "rt-multi-thread", "macros",]

[dependencies.tonic]
version = "0.8.3"
features = [ "tls",]

[dependencies.clap]
version = "3.2.22"
features = [ "derive",]

[target."cfg(target_family = \"unix\")".build-dependencies]
protobuf-src = "1.1.0"
