[package]
name = "vegafusion-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]] # Bin to run the HelloWorld gRPC server
name = "helloworld-server"
path = "src/server.rs"

[[bin]] # Bin to run the HelloWorld gRPC client
name = "helloworld-client"
path = "src/client.rs"

[[bin]] # Bin to run the VegaFusion Runtime as gRPC service
name = "vegafusion-server"
path = "src/vegafusion-server.rs"

[dependencies]
vegafusion-core = {path = "../vegafusion-core", features=["datafusion", "tonic_support"]}
vegafusion-rt-datafusion = {path = "../vegafusion-rt-datafusion"}
prost = "0.9.0"
tokio = {version = "1.17.0", features=["rt-multi-thread", "macros"]}
tonic = {version="0.6.2", features=["tls"]}
tower = {version = "0.4"}
tokio-tungstenite = { version="0.17.0" }
futures-util="0.3.21"

[dev-dependencies]
serde_json = "1.0.68"

[build-dependencies]
tonic-build = "0.6"