[[bin]]
name = "vegafusion-server"
path = "src/main.rs"

[package]
name = "vegafusion-server"
version = "0.6.1"
edition = "2021"
license = "AGPL-3.0-or-later"

[dependencies]
prost = "0.10.3"
futures-util = "0.3.21"
regex = "^1.5.5"
tonic-web = "0.3.0"

[dev-dependencies]
serde_json = "1.0.81"
assert_cmd = "2.0"
predicates = "2.1"

[build-dependencies]
tonic-build = "0.7.2"
prost-build = "0.10.3"

[dependencies.vegafusion-core]
path = "../vegafusion-core"
features = [ "tonic_support",]

[dependencies.vegafusion-rt-datafusion]
path = "../vegafusion-rt-datafusion"

[dependencies.tokio]
version = "1.18.1"
features = [ "rt-multi-thread", "macros",]

[dependencies.tonic]
version = "0.7.2"
features = [ "tls",]

[dependencies.clap]
version = "3.1.0"
features = [ "derive",]
