name: vegafusion_jupyter_dev
channels:
  - conda-forge
dependencies:
  - python =3.10
  - yarn
  - maturin
  - jupyterlab
  - jupyter-packaging
  - conda-lock
  - pip
  - jupytext
  - pytest >=4.6
  - pytest-cov
  - vega_datasets
  - voila
  - nbval
  - jupytext
  - selenium
  - scikit-image
  - tenacity
  - flaky
  - click
  - toml
  - python-duckdb >=0.7.1
  - polars
