[package]
name = "vegafusion-common"
version = "1.0.3"
edition = "2021"

[features]
pyarrow = [ "pyo3" ]
json = ["serde_json", "arrow/json"]
prettyprint = ["arrow/prettyprint"]

[dependencies]
thiserror = "^1.0.29"

[dependencies.sqlparser]
version = "0.30.0"
optional = true

[dependencies.serde_json]
version = "1.0.91"
default_features = false
optional = true

[dependencies.arrow]
version = "29.0.0"
default_features = false
features = ["ipc"]

[dependencies.datafusion-common]
version = "~16.1.0"
git = "https://github.com/jonmmease/arrow-datafusion.git"
rev = "1e6438de31219b284df9b83f25ca36ddb1184f22"

[dependencies.datafusion-expr]
version = "~16.1.0"
git = "https://github.com/jonmmease/arrow-datafusion.git"
rev = "1e6438de31219b284df9b83f25ca36ddb1184f22"


[dependencies.pyo3]
version = "0.17.1"
optional = true
