name: build_test
on: [push]
jobs:
  rust-fmt-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: True
      - name: Check cargo fmt compliance
        run: cargo fmt --all -- --check
      - name: Check for clippy warnings
        run: cargo clippy

#  test-rust:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v2
#      - name: Install apt system dependencies needed to build nodecanvas
#        run: |
#          sudo apt-get install -y libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
#      - name: Install latest stable Rust toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#      - name: Install node
#        uses: actions/setup-node@v2
#        with:
#          node-version: '17'
#      - name: Install test node dependencies
#        run: |
#          cd vegafusion-rt-datafusion/tests/util/vegajs_runtime
#          npm install
#      - name: Cache rust dependencies
#        uses: Swatinem/rust-cache@v1
#        with:
#          cache-on-failure: True
#      - name: Run Rust Tests
#        uses: actions-rs/cargo@v1
#        with:
#          command: test
#          args: --all-features

#  build-vegafusion-python:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v2
#      - uses: conda-incubator/setup-miniconda@v2
#        with:
#          auto-update-conda: true
#          activate-environment: vegafusion_dev
#          miniforge-version: latest
#          environment-file: python/vegafusion-jupyter/conda-linux-64.lock.yml
#      - name: Install latest stable Rust toolchain
#        uses: actions-rs/toolchain@v1
#        with:
#          toolchain: stable
#          override: true
#      - name: maturin build
#        shell: bash -l {0}
#        run: |
#          cd vegafusion-python/
#          maturin build --release
#      - name: Upload wheel artifacts
#        uses: actions/upload-artifact@v2
#        with:
#          name: vegafusion-python-wheels
#          path: |
#            target/wheels/*.whl

  build-vegafusion-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '17'
      - name: Build package
        run: |
          cd vegafusion-wasm/
          wasm-pack build --release
      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v2
        with:
          name: vegafusion-wasm-packages
          path: vegafusion-wasm/pkg