name: build_test
on: [push]
jobs:
  test-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install latest stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install test node dependencies
        run: |
          cd vegafusion-rt-datafusion/tests/util/vegajs_runtime
          npm install
      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v1
      - name: Check cargo fmt compliance
        run: cargo fmt --all -- --check
      - name: Run Rust Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
