name: build
on:
  pull_request:
    types: [ opened, synchronize ]
jobs:

  build-vegafusion-server-win-64:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        i:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
    steps:
      - name: Check out repository code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # pin@v3.5.2
      - name: Pixi command
        run: |
          .\pixi.exe install -vvv
          .\pixi.exe run python --version
